//! Lana VM core. Rust ownership and byte accounting enforce the 256 MiB limit.

pub mod backend;
pub mod derivation;
pub mod heap;
pub mod inspect;
pub mod metal;
pub mod rng;
pub mod sha256;
pub mod state;
pub mod state_dist;
pub mod tensor;
pub mod unicode_case;
pub mod value;
pub mod vm;

pub use derivation::{Derivation, DerivationExactness, DerivationKind, DerivationOutcome};
pub use inspect::{inspect, InspectFormat};
pub use rng::Rng;
pub use state::{State, StateValue};
pub use value::{
    Adt, CapabilityToken, Claim, EffectReceipt, JointKind, JointRow, JointState, PathAlternative,
    PathSet, PlannedEffect, Possibility, Reactive, ReactiveKind, ReactiveVersion,
    RelationshipKind, SharedCommit, SharedInformation, SharedObservation, SharedState,
    SharedVersion, Task, Tensor, TensorDevice, Value, ValueKind, VmError, ADT_UNKNOWN_VARIANT, LANA_CAPABILITY_ADMIN,
    LANA_CAPABILITY_OBSERVE, LANA_CAPABILITY_READ,
};
pub use vm::{
    exact_support_name, resolution_reason_name, resource_kind_name, Frame, History, HistoryPolicy,
    Vm, RootedValue, LANA_EXACT_SUPPORT_AVAILABLE, LANA_EXACT_SUPPORT_UNAVAILABLE, LANA_EXACT_SUPPORT_UNKNOWN,
    LANA_RESOLUTION_REASON_CANCELLED, LANA_RESOLUTION_REASON_CONTRADICTION,
    LANA_RESOLUTION_REASON_INVALID_CONDITIONING, LANA_RESOLUTION_REASON_MULTIPLE_ALTERNATIVES,
    LANA_RESOLUTION_REASON_NONE, LANA_RESOLUTION_REASON_NO_ALTERNATIVES,
    LANA_RESOLUTION_REASON_RESOURCE_LIMIT, LANA_RESOLUTION_REASON_UNSUPPORTED_EXACT,
    LANA_RESOURCE_INSTRUCTIONS, LANA_RESOURCE_MEMORY, LANA_RESOURCE_PATHS, LANA_RESOURCE_SAMPLES,
    LANA_RESOURCE_TASKS, LANA_RESOURCE_TIME, LANA_HOST_STORE_OPEN, LANA_HOST_STORE_PUT,
    LANA_HOST_STORE_GET, LANA_HOST_STORE_DELETE, LANA_HOST_STORE_COMMIT, LANA_HOST_STORE_SCAN,
    LANA_HOST_STORE_CURRENT_REVISION, LANA_HOST_POLICY_EVALUATE, LANA_HOST_POLICY_STORE_DECISION,
    LANA_HOST_LEDGER_APPEND, LANA_HOST_LEDGER_QUERY, LANA_HOST_STORE_GET_AT,
    LANA_HOST_STORE_SNAPSHOT, LANA_HOST_STORE_COMMIT_IF, LANA_HOST_ADAPTER_LOAD,
    LANA_HOST_ADAPTER_FETCH, LANA_HOST_FFI_DECLARE, LANA_HOST_FFI_LOAD, LANA_HOST_FFI_CALL,
    LANA_HOST_DENSITY_OPERATOR, LANA_HOST_POVM,
    LANA_HOST_CHANNEL, LANA_HOST_OBSERVABLE, LANA_HOST_TENSOR_PRODUCT, LANA_HOST_PARTIAL_TRACE,
    LANA_HOST_MEASURE_WITH, LANA_HOST_APPLY_TO, LANA_HOST_EXPECT, LANA_HOST_MIX,
    LANA_HOST_TRACE_DISTANCE, LANA_HOST_IS_SEPARABLE, LANA_HOST_TO_STATE,
    LANA_HOST_STATE_TENSOR, LANA_HOST_APPEND, LANA_HOST_MEASURE, LANA_HOST_TRANSFORM,
    LANA_HOST_EXECUTION_CAPABILITY, LANA_HOST_EXECUTION_AUTHORIZE, LANA_HOST_EXECUTION_EXECUTE,
    LANA_HOST_FUTURE_MESSAGE, LANA_HOST_DATASET_SOURCE, LANA_HOST_DATASET_QUERY, LANA_HOST_DATASET_APPLY,
    LANA_HOST_DATASET_SNAPSHOT, LANA_HOST_DATASET_EVIDENCE, LANA_HOST_DATASET_EXCLUSIONS,
    LANA_HOST_DOCUMENT_EXTRACT, LANA_HOST_DATASET_SQLITE, LANA_HOST_RULES_LEARN, LANA_HOST_RULES_PREDICT,
    LANA_HOST_RULES_SAVE, LANA_HOST_RULES_ADD_COUNTEREXAMPLE, LANA_HOST_RULES_INSPECT,
    LANA_HOST_RULES_ROLLBACK,
    LANA_HOST_TREES_FIT, LANA_HOST_TREES_PREDICT, LANA_HOST_TREES_EXPLAIN,
    LANA_HOST_TREES_SAVE, LANA_HOST_TREES_LOAD,
    LANA_HOST_EVALUATION_WALK_FORWARD,
};
