[package]
name = "lana-fuzz-targets"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
lana-fuzz = { path = "../tools/rust/lana-fuzz" }
libfuzzer-sys = "0.4"

[[bin]]
name = "lana_bytecode"
path = "fuzz_targets/lana_bytecode.rs"
test = false
doc = false
bench = false

[workspace]
