#!/usr/bin/env python3
"""Generate the Unicode simple case-mapping tables consumed by both VMs.

Reads UnicodeData.txt (pinned to Unicode 15.1.0) and emits:
  - vm/include/unicode_case.h   (C11 static tables + binary-search lookup)
  - vm/rust/lana-vm/src/unicode_case.rs (Rust static tables + lookup)

Only *simple* (1:1) case mappings are emitted: UnicodeData.txt field 12
(uppercase mapping) and field 13 (lowercase mapping). Characters whose case
mapping is multi-character (e.g. U+00DF LATIN SMALL LETTER SHARP S -> "SS")
have an empty simple mapping and are left unchanged, matching the LIP-021
decision to implement simple case mapping rather than full case folding.

Usage:
    python3 tools/gen_unicode_tables.py [path/to/UnicodeData.txt]

If no path is given, the pinned UnicodeData.txt is downloaded from unicode.org.
"""

import sys
import urllib.request

UNICODE_VERSION = "15.1.0"
UNICODE_DATA_URL = (
    "https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt"
)

C_HEADER_PATH = "vm/include/unicode_case.h"
RUST_PATH = "vm/rust/lana-vm/src/unicode_case.rs"


def load_lines(path):
    if path is None:
        print(f"downloading UnicodeData.txt {UNICODE_VERSION} ...", file=sys.stderr)
        with urllib.request.urlopen(UNICODE_DATA_URL) as response:
            return response.read().decode("utf-8").splitlines()
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read().splitlines()


def parse_mappings(lines):
    upper = []  # (from, to) where to is the simple uppercase mapping
    lower = []  # (from, to) where to is the simple lowercase mapping
    for line in lines:
        if not line or line.startswith("#"):
            continue
        fields = line.split(";")
        if len(fields) < 14:
            continue
        cp = int(fields[0], 16)
        upper_field = fields[12].strip()
        lower_field = fields[13].strip()
        if upper_field:
            upper.append((cp, int(upper_field, 16)))
        if lower_field:
            lower.append((cp, int(lower_field, 16)))
    upper.sort()
    lower.sort()
    return upper, lower


def emit_c_header(upper, lower):
    lines = []
    lines.append("#ifndef LANA_UNICODE_CASE_H")
    lines.append("#define LANA_UNICODE_CASE_H")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Generated by tools/gen_unicode_tables.py from UnicodeData.txt")
    lines.append(f" * {UNICODE_VERSION}. Simple (1:1) case mappings only; do not edit by hand. */")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint32_t from;")
    lines.append("    uint32_t to;")
    lines.append("} LanaCaseMapping;")
    lines.append("")
    lines.append("static const LanaCaseMapping LANA_UPPER_MAP[] = {")
    for from_cp, to_cp in upper:
        lines.append(f"    {{0x{from_cp:06X}u, 0x{to_cp:06X}u}},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t LANA_UPPER_MAP_COUNT = {len(upper)}u;")
    lines.append("")
    lines.append("static const LanaCaseMapping LANA_LOWER_MAP[] = {")
    for from_cp, to_cp in lower:
        lines.append(f"    {{0x{from_cp:06X}u, 0x{to_cp:06X}u}},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t LANA_LOWER_MAP_COUNT = {len(lower)}u;")
    lines.append("")
    lines.append("static inline uint32_t lana_unicode_upper(uint32_t cp) {")
    lines.append("    size_t lo = 0u, hi = LANA_UPPER_MAP_COUNT;")
    lines.append("    while (lo < hi) {")
    lines.append("        size_t mid = lo + (hi - lo) / 2u;")
    lines.append("        if (LANA_UPPER_MAP[mid].from < cp) { lo = mid + 1u; }")
    lines.append("        else { hi = mid; }")
    lines.append("    }")
    lines.append("    if (lo < LANA_UPPER_MAP_COUNT && LANA_UPPER_MAP[lo].from == cp) {")
    lines.append("        return LANA_UPPER_MAP[lo].to;")
    lines.append("    }")
    lines.append("    return cp;")
    lines.append("}")
    lines.append("")
    lines.append("static inline uint32_t lana_unicode_lower(uint32_t cp) {")
    lines.append("    size_t lo = 0u, hi = LANA_LOWER_MAP_COUNT;")
    lines.append("    while (lo < hi) {")
    lines.append("        size_t mid = lo + (hi - lo) / 2u;")
    lines.append("        if (LANA_LOWER_MAP[mid].from < cp) { lo = mid + 1u; }")
    lines.append("        else { hi = mid; }")
    lines.append("    }")
    lines.append("    if (lo < LANA_LOWER_MAP_COUNT && LANA_LOWER_MAP[lo].from == cp) {")
    lines.append("        return LANA_LOWER_MAP[lo].to;")
    lines.append("    }")
    lines.append("    return cp;")
    lines.append("}")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def emit_rust(upper, lower):
    lines = []
    lines.append("//! Generated by tools/gen_unicode_tables.py from UnicodeData.txt")
    lines.append(f"//! {UNICODE_VERSION}. Simple (1:1) case mappings only; do not edit by hand.")
    lines.append("")
    lines.append("pub static UPPER_MAP: &[(u32, u32)] = &[")
    for from_cp, to_cp in upper:
        lines.append(f"    (0x{from_cp:06X}, 0x{to_cp:06X}),")
    lines.append("];")
    lines.append("")
    lines.append("pub static LOWER_MAP: &[(u32, u32)] = &[")
    for from_cp, to_cp in lower:
        lines.append(f"    (0x{from_cp:06X}, 0x{to_cp:06X}),")
    lines.append("];")
    lines.append("")
    lines.append("pub fn unicode_upper(cp: u32) -> u32 {")
    lines.append("    match UPPER_MAP.binary_search_by_key(&cp, |&(from, _)| from) {")
    lines.append("        Ok(index) => UPPER_MAP[index].1,")
    lines.append("        Err(_) => cp,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("pub fn unicode_lower(cp: u32) -> u32 {")
    lines.append("    match LOWER_MAP.binary_search_by_key(&cp, |&(from, _)| from) {")
    lines.append("        Ok(index) => LOWER_MAP[index].1,")
    lines.append("        Err(_) => cp,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else None
    lines = load_lines(path)
    upper, lower = parse_mappings(lines)
    print(f"upper mappings: {len(upper)}, lower mappings: {len(lower)}", file=sys.stderr)

    with open(C_HEADER_PATH, "w", encoding="utf-8") as handle:
        handle.write(emit_c_header(upper, lower))
    with open(RUST_PATH, "w", encoding="utf-8") as handle:
        handle.write(emit_rust(upper, lower))
    print(f"wrote {C_HEADER_PATH} and {RUST_PATH}")


if __name__ == "__main__":
    main()
