set(initialize "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{}}")
set(shutdown "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"shutdown\",\"params\":null}")
set(exit_message "{\"jsonrpc\":\"2.0\",\"method\":\"exit\"}")
string(LENGTH "${initialize}" initialize_length)
string(LENGTH "${shutdown}" shutdown_length)
string(LENGTH "${exit_message}" exit_length)
set(input "Content-Length: ${initialize_length}\r\n\r\n${initialize}Content-Length: ${shutdown_length}\r\n\r\n${shutdown}Content-Length: ${exit_length}\r\n\r\n${exit_message}")
set(input_path "${OUTPUT}.input")
file(WRITE "${input_path}" "${input}")
execute_process(COMMAND "${LANA}" lsp INPUT_FILE "${input_path}"
                OUTPUT_FILE "${OUTPUT}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "LSP session failed: ${result}")
endif()
file(READ "${OUTPUT}" response)
if(NOT response MATCHES "lana-lsp" OR NOT response MATCHES "renameProvider")
    message(FATAL_ERROR "LSP initialize response is incomplete")
endif()
