file(REMOVE_RECURSE "${ROOT}")
file(REMOVE_RECURSE "${ROOT}-dep")
execute_process(COMMAND "${LANA}" new "${ROOT}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "lana new failed")
endif()
execute_process(COMMAND "${LANA}" new "${ROOT}-dep" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "dependency project creation failed")
endif()
file(APPEND "${ROOT}/lana.toml" "dep = \"../project-workflow-dep\"\n")
if(NOT EXISTS "${ROOT}/src/main.lana" OR
   NOT EXISTS "${ROOT}/src/belief.lana" OR
   NOT EXISTS "${ROOT}/tests/main_test.lana")
    message(FATAL_ERROR "lana new did not create the first-program module")
endif()
file(READ "${ROOT}/src/main.lana" main_source)
file(READ "${ROOT}/tests/main_test.lana" test_source)
if(NOT main_source MATCHES "import \"./belief.lana\" as belief" OR
   NOT test_source MATCHES "import \"../src/belief.lana\" as belief")
    message(FATAL_ERROR "generated project does not exercise module imports")
endif()
foreach(command IN ITEMS build check test run doc)
    execute_process(COMMAND "${LANA}" ${command} WORKING_DIRECTORY "${ROOT}"
                    RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "lana ${command} failed")
    endif()
endforeach()
execute_process(COMMAND "${LANA}" fmt WORKING_DIRECTORY "${ROOT}"
                RESULT_VARIABLE result)
execute_process(COMMAND "${LANA}" fmt --check WORKING_DIRECTORY "${ROOT}"
                RESULT_VARIABLE check_result)
if(NOT result EQUAL 0 OR NOT check_result EQUAL 0)
    message(FATAL_ERROR "formatter is not idempotent")
endif()
if(NOT EXISTS "${ROOT}/lana.lock" OR NOT EXISTS "${ROOT}/docs/api.md" OR
   NOT IS_DIRECTORY "${ROOT}/.lana/cache")
    message(FATAL_ERROR "project artifacts are incomplete")
endif()
file(READ "${ROOT}/lana.lock" lock)
if(NOT lock MATCHES "dependency.dep")
    message(FATAL_ERROR "local dependency was not locked")
endif()
file(REMOVE_RECURSE "${ROOT}")
file(REMOVE_RECURSE "${ROOT}-dep")
